### ISSUE TITLE
API Returned HTTP Status Code of 422

### ISSUE THREAD

**Issue by ghost** [jnormington/trello-to-clubhouse.io#11]
Hello Jon,

First, thanks for contributing and easing the pain of transfer. Unfortunately, whenever I reach the end step of `Importing Trello Cards to Clubhouse` I receive the above mentioned error (available in the title), so basically I get `Unprocessable Entity`. Any ideas on a fix, or what I might be doing wrong ?

P.S: Also I think I came up to another issue, that I would like to talk to you.

Thanks.

**Comment by jnormington** [comment]
Hey @harunb-slice,

Sorry you experiencing some issues with the trello-to-clubhouse migration tool. We just the other day upgrade the tool to v2 API to fix multi workflow support.

I'm not sure in your scenario why it is returning 422 from the Clubhouse API. 

I've created a debugging version of the migration tool to also print out the body of the response so that we can see what errors are being returned from the API.

It will look something similar to the below.

```
Importing trello cards into Clubhouse...
Trello Card Link                         Import Status     Error/Story ID

https://trello.com/c/ffUhgfDu            Failed            API Returned HTTP Status Code of 400 with body: {"message":"The request included invalid or missing parameters.","errors":{"file_ids":["not",["set?",null]]}}
https://trello.com/c/EUZFNWsh            Failed            API Returned HTTP Status Code of 400 with body: {"message":"The request included invalid or missing parameters.","errors":{"file_ids":["not",["set?",null]]}}
https://trello.com/c/FcsZeUVf            Failed            API Returned HTTP Status Code of 400 with body: {"message":"The request included invalid or missing parameters.","errors":{"file_ids":["not",["set?",null]]}}
```
Would you mind downloading the zip attached below and running the debugging version for your operating system.

[trello-to-clubhouse-debug-version.zip](https://github.com/jnormington/trello-to-clubhouse.io/files/1384669/trello-to-clubhouse-debug-version.zip)

Could you then let me know the following;

 - The options you selected throughout
 - The response output as shown above (feel free to omit any personal info)

**Comment by jnormington** [comment]
Hey @harunb-slice,

Just wondered if you had seen my previous message and/or had a chance to have a try with the debugged version of the binary ?

**Comment by ghost** [comment]
Hello @jnormington,

Terribly sorry for the delay (managed to get myself sick). I did try your `debug-version` and was successfully able to transfer files. Didn't receive the `API 400's` while using it. By any chance that there is a difference between the debug version that you send me and the master ?

**Comment by jnormington** [comment]
Hi @harunb-slice,

No worries - I think the issue was two days before you raised an issue - I fixed some bug with workflows - now that multiple teams are supported. I released a new version, but forgot to update the readme 😞  - so after a day on my first comment I realised this.

I updated it - but I assume the bug you probably might have been running into was probably the multiple workflows across teams, as the project and team much match for the same team.

Sorry for the confusion around that

Is the other issue you wanted to talk about also fixed ?

**Comment by ghost** [comment]
Actually yes. The other issue was being able to see multiple workflows across teams, but not being able to choose a different workflow since they were all marked with values from 1-5 and it was repetitive for 5 different (team) workflows, thus couldn't choose the proper one. 

Nonetheless, the debug version worked flawlessly and I was able to transfer everything successfully. If you updated the master branch than everything should be fine.

Thanks for the fast response and taking care of this, also sorry for the delays. I think it's safe to mark this issue as resolved 👍

**Comment by jnormington** [comment]
Great thanks for the update @harunb-slice
