### ISSUE TITLE
Is it possible to migrate the Assignee detail from Trello to Clubhouse?

### ISSUE THREAD

**Issue by meganchinburg** [jnormington/trello-to-clubhouse.io#3]
Hi,
I love this tool, it's quite slick and just works! I am considering a migration of a semi-large team (50 people spread across 64 boards) and I'd love to avoid re-assigning all the cards once they are migrated.

I am not familiar with Go, so it's not immediately obvious to me how to grab the Member from trello card, match with member in Clubhouse and update the card during the migration process. Is this a feature you have considered adding?  If not, is there a technical or logistical reason? 
Thank you!

**Comment by jnormington** [comment]
Thanks @meganchinburg - Sorry I didn't get notified of this issue being raised. It shouldn't be too hard to do but the reason I didn't support it was because the names from Trello to Clubhouse were so different, for us at least I opted for missing it off.

But if this is something that would be useful - I would be more than happy to support it mapping directly - maybe it should have a csv mapping in case of differences - what do you think ?

Also would you expect if a name isn't found in clubhouse that it falls back and displays on the output the assignee status as well ?

It can be part of the questions throughout the process.

Let me know your thoughts I could have a little look this week.

**Comment by meganchinburg** [comment]
Hi @jnormington, thanks for getting back to me on this! I think having a CSV mapping would make it pretty low maintenance, at least for our size of org (<30 engineers), particularly if it was difficult to compare users across systems. I didn't check if you can access email addresses in both APIs.

**Comment by jnormington** [comment]
Hey @meganchinburg,

I completely forgot about email addresses :) - I just checked we can get email from both services. I will have a little look now at starting this and see how far I get :)

If we have an account that is present in Trello but not in Clubhouse - for now I think I will list them out and ask to map them to another account. This way you can know if anyone doesn't have an account for example.

Seeing as I am doing the assignee I might as well also map the correct creator of the original ticket as well :)

**Comment by jnormington** [comment]
Hey @meganchinburg 

It seems that the go-trello package we are using gives two fields Email, NewEmail on the Member struct. However during testing the implementation - it appears that you can't get the email address from Trello when checking their API.

Therefore we have the following options which are possible
 - Use the full name from both services (we already list the ones that don't match - so internally you can chase users that don't match)
 - CSV file mapping

Which would you prefer ?

**Comment by meganchinburg** [comment]
Either one would work for my use case as I don't have any name duplicates.
For larger teams it might be useful to have csv mapping option. I would be
happy with either.
Thank you!

**Comment by jnormington** [comment]
Hey @meganchinburg,

Sorry for the delay on this, so between yesterday evening and this evening I have finished the implementation for migrating Trello cards with card creator, members, comment creator.

It uses the CSV mapping solution, but instead of you having to build the CSV from scratch it does this for you by making a "best guess" of the mapping only based on the name - (so if there are duplicates names - this allows you to correct).

Once the CSV is generated you can modify the CSV to be correct while the program waits. You also have the option to not regenerate the file - if you have already perfected the csv - otherwise it will just overwrite it.

I have given it a quick whiz and all appears to be working, but before I merge into master - would you mind giving it a spin/test with one of your boards please ?

The new binaries are below - any feedback welcome on any issues you may find.

[trello_binaries.zip](https://github.com/jnormington/trello-to-clubhouse.io/files/628373/trello_binaries.zip)

Once you sign off I will merge this.

Thanks again!

**Comment by meganchinburg** [comment]
Awesome! Thanks! I can take a look on Monday

**Comment by meganchinburg** [comment]
Hey @jnormington it works great! Thanks.

**Comment by jnormington** [comment]
Thanks @meganchinburg - will close this issue and merge and update the docs
