### ISSUE TITLE
Selecting workflow state

### ISSUE THREAD

**Issue by bcavill** [jnormington/trello-to-clubhouse.io#9]
When selecting a workflow to import your trello cards into if there are more than 10 options you can't select a workflow properly because once the program gets to 9 it starts listing the options from 0 again.

E.G: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2

**Comment by jnormington** [comment]
Hey @bcavill 

Thanks for filing the issue - I think I see the issue [here](https://github.com/jnormington/trello-to-clubhouse.io/blob/master/clubhouse_options.go#L111-L124)

Basically this has a nested for loop and I think at the time of writing I thought it wasn't possible to have multiple workflows therefore if you have multiple workflows it will reset back to zero the states for each workflow. I guess you must have 9 states in the first workflow ?

Either way it would only ever select the first workflow based on your selection

https://github.com/jnormington/trello-to-clubhouse.io/blob/master/clubhouse_options.go#L124

I'll look at fixing this so it displays correctly and selects the correct workflow/state

**Comment by jnormington** [comment]
Hey @bcavill 

I think I've implemented a fix - it seems that since the introduction of teams now means an account can have multiple workflows which we didn't cater for when this was originally written - we've had to upgrade to use v2 API to get access to new attributes for this to be a proper fix and reduce error from the selection stage.

I think from some testing I caught most of the little tweaks required to end to end now.

You can find new alpha binary release [here](https://github.com/jnormington/trello-to-clubhouse.io/releases/tag/v0.3.0.alpha)

https://github.com/jnormington/trello-to-clubhouse.io/releases/tag/v0.3.0.alpha

Would you mind giving it a spin please and feeding back before I merge into master please ?

**Comment by bcavill** [comment]
Hey @jnormington 

This works perfectly. The only thing is that I was a little confused at first as I was given the option Default - Unscheduled even though my Team for the project I selected is called Ticketing, so I originally thought I was seeing the default team workflows.

**Comment by jnormington** [comment]
@bcavill great thanks for verifying that also good point - this is what the workflow name is - but do you think as a team can only have one workflow - and now that we are limiting the workflows based on the project you selected - do you think removing the workflow name and only displaying the states would be suffice and remove this kind of confusion ? 

Or could we just add some better text (in case multi team workflows are ever supported) - to say
that 

`Please select a workflow/state linked to project x to import the cards to`

**Comment by bcavill** [comment]
@jnormington 
I wouldn't add better text unless it's not a lot of work as they might never add multi team workflows and I'm not sure how much use multiple workflows for a project would ever be.

**Comment by jnormington** [comment]
Thanks @bcavill the text change was a one line update. I've now merged in master and released 0.3.0 officially.

Thanks again for raising the issue and helping with the testing!
